# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: [push]

jobs:
  test:
    name: "Ruby ${{ matrix.ruby-version }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.4']
        allow-failure: [false]
        frozen-string: [true]
        include:
          - ruby-version: '2.4'
            allow-failure: false
            frozen-string: true
          - ruby-version: '2.7'
            allow-failure: false
            frozen-string: true
          - ruby-version: '3.0'
            allow-failure: false
            frozen-string: true
          - ruby-version: '3.1'
            allow-failure: false
            frozen-string: true
          - ruby-version: '3.2'
            allow-failure: false
            frozen-string: true
          - ruby-version: '3.3'
            allow-failure: false
            frozen-string: true
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rspec
